### ISSUE TITLE
Error: Diaphora hands on dialogs

### ISSUE THREAD

**Issue by tmr232** [joxeankoret/diaphora#47] opened 2015-12-21 08:37 UTC
When exporting the database and trying to overwrite an existing file, a dialog appears, asking whether to overwrite the original file. If the dialog is not closed within a few seconds, IDA pops a "running Python script" window, and the whole thing just locks up.
![image](https://cloud.githubusercontent.com/assets/1386239/11926584/ac4c7638-a7ce-11e5-8526-a5e474ecaf76.png)

As the Python code is waiting for the UI, pressing `Cancel` does not help either.

**Comment by joxeankoret** [comment] 2015-12-21 19:42
It happens with 6.8 or 6.9 BETA? BTW, it looks like a bug on IDA itself.

**Comment by tmr232** [comment] 2015-12-21 20:12
I don't think it is a bug in IDA. I have PySide installed separately, but
since it on the Python Path, it gets loaded. It even gets loaded before
IDA's PySide.
So 6.8 works fine, and 6.9 imports PySide instead.

It happens with 6.8 or 6.9 BETA? BTW, it looks like a bug on IDA itself.

—
Reply to this email directly or view it on GitHub
<https://github.com/joxeankoret/diaphora/issues/47#issuecomment-166400489>.

**Comment by tmr232** [comment] 2015-12-21 20:17
6.8

**Comment by joxeankoret** [comment] 2015-12-23 10:47
Sorry, I cannot reproduce neither with IDA 6.9 nor with IDA 6.8 in Linux or Windows (10). I waited for ~30 minutes and the "Running Python script" window doesn't appear until I close the "Export database..." dialogue.

**Comment by tmr232** [comment] 2015-12-23 12:04
This is weird, as it reproduces for me every single time. I guess I'll have to look into it myself.

**Comment by joxeankoret** [comment] 2015-12-23 12:23
Uhm... may it have something to do with your own PySide installation (https://github.com/joxeankoret/diaphora/issues/48#issue-123263427)?

**Comment by tmr232** [comment] 2015-12-23 12:55
Doesn't seem like it, I get the same results on IDA 6.9 with latest version of diaphora (so PySide is not imported).

**Comment by joxeankoret** [comment] 2015-12-23 20:20
Uhm.. can you try running the following in a script (not in the script command, as a script file) and see if the same problem reproduces?

```
import idaapi

idaapi.askyn_c(0, "Export database already exists. Do you want to overwrite it?")
```

**Comment by joxeankoret** [comment] 2016-04-07 15:22
I'm closing this issue as I haven't got feedback since long time. Feel free to re-open it if you still experience it.

**Closed by joxeankoret** 2016-04-07 15:22 UTC
