### ISSUE TITLE
UnboundLocalError in diaphora_ida.py

### ISSUE THREAD

**Issue by pkooiman** [joxeankoret/diaphora#190] opened 2020-06-24 15:05 UTC
Hi,
I'm getting a "referenced  before assignement" on line 1764 of diaphora_ida.py.

```

   for pred_block in block.preds():
        if pred_block.end_ea == 0:
          continue

        try:
          bb_relations[pred_block.start_ea - image_base].append(block.start_ea - image_base)
        except KeyError:
          bb_relations[pred_block.start_ea - image_base] = [block.start_ea - image_base]

        edges += 1
        outdegree += 1
        if succ_block.id not in dones:    #<--- offending line
          dones[succ_block] = 1
```

Should that be pred_block instead of succ_block in the final if? I get the impression that succ_block is indeed not defined within this loop.

Thanks
Peter

**Comment by joxeankoret** [comment] 2020-06-25 09:32
That's a weird bug because nobody hit it until today, as far as I can tell. Thanks for reporting! I'm investigating it.

**Comment by joxeankoret** [comment] 2020-06-25 09:33
By the way, if you can share a sample to reproduce the issue that would significantly help me on this task.

**Comment by pkooiman** [comment] 2020-06-25 09:50
My boss won't let me, NDAs etc, I'm really sorry about that! 
And yes you're right, I myself use diaphora all the time and this is the first time I hit this error.
For kicks, I changed succ_block to pred_block and it seems to work fine. But as I have no idea what is actually happening that does not mean much..

**Comment by joxeankoret** [comment] 2020-06-25 10:25
>My boss won't let me, NDAs etc, I'm really sorry about that!
It's OK, I understand.

> For kicks, I changed succ_block to pred_block and it seems to work fine. But as I have no idea what is actually happening that does not mean much..
After taking a look to it, this is a bug that is there since pretty much forever. I'm launching the testing suite to verify the patch and I will commit the change "soon".

Thanks again for reporting this ancient bug!

**Comment by pkooiman** [comment] 2020-06-25 10:32
Thank you for your quick reaction and for your great tool!

**Comment by joxeankoret** [comment] 2020-06-25 11:46
You're very welcome! Fixed with https://github.com/joxeankoret/diaphora/commit/b019145d1efdcadbdafd6ea95f3d579bc698fbda.

**Closed by joxeankoret** 2020-06-25 11:46 UTC
