### ISSUE TITLE
Silent failures could be made a little louder

### ISSUE THREAD

**Issue by Talos878** [joxeankoret/diaphora#235] opened 2022-09-26 22:10 UTC
I am returning to using diaphora headless for the first time in a while and while playing with the command line noticed this trend

These two work
ida64 -S"/Users/talos/diaphora/diaphora_ida.py" /Users/talos/Documents/boot

ida64 -A -B -S"/Users/talos/diaphora/diaphora_ida.py" /Users/talos/Documents/boot

This silently fails and corrupts the database
ida64 -S"diaphora_ida.py" /Users/talos/Documents/boot

This silently fails and destroys the database
ida64 -S"diaphora_ida.py /Users/talos/Documents/iBoot" /Users/talos/Documents/boot.i64

It would be nice to have some warnings in the situations where corruption happens. Am I giving arguments to some valid use case in a strange way here that is causing some normal functionality to run halfway and than never fix up the database?

**Comment by joxeankoret** [comment] 2022-10-13 07:43
Hi! I don't think it has anything to do with Diaphora, or I do not properly understand the problem. The problem is that IDA doesn't support relative paths for scripts so, my guess is that it's just recreating your I64 database, isn't it? If that's the problem, I don't think I can do anything from Diaphora to prevent this, as it's happening even before Diaphora runs.

**Comment by joxeankoret** [comment] 2022-11-24 16:21
I'm closing it for now. Feel free to reopen if you have problems.

**Closed by joxeankoret** 2022-11-24 16:21 UTC
