### ISSUE TITLE
Type Error when using "Import all data for sub_ Functions"

### ISSUE THREAD

**Issue by ionescu007** [joxeankoret/diaphora#7] opened 2015-04-09 03:50 UTC
Already have a bunch of stuff imported, did a second-pass diff, tried this option, and got this:

[Wed Apr 08 20:49:00 2015] Importing type libraries...
[Wed Apr 08 20:49:00 2015] import_all(): Expected an ea_t type
Traceback (most recent call last):
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 1538, in import_all_auto
    self.do_import_all_auto(items)
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 1497, in do_import_all_auto
    self.import_til()
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 1077, in import_til
    cur.execute(sql)
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 260, in OnCommand
    self.bindiff.import_one(self.items[n])
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 1128, in import_one
    self.do_import_one(ea1, ea2, True)
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 1441, in do_import_one
    cur.execute(sql, (ea2,))
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 260, in OnCommand
    self.bindiff.import_one(self.items[n])
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 1128, in import_one
    self.do_import_one(ea1, ea2, True)
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 1441, in do_import_one
    cur.execute(sql, (ea2,))
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 260, in OnCommand
    self.bindiff.import_one(self.items[n])
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 1130, in import_one
    new_func = self.read_function(str(ea1))
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 715, in read_function
    func = get_func(f)
  File "C:\Program Files (x86)\IDA 6.7\python\idaapi.py", line 29628, in get_func
    return _idaapi.get_func(*args)
TypeError: Expected an ea_t type
Caching 'Partial matches'... ok

**Comment by ionescu007** [comment] 2015-04-09 03:55
This may be related to Issue #8 because I stuck in the mode where I could no longer import one-by-one. After doing the "Double-click" trick, import sub_ worked!

**Comment by joxeankoret** [comment] 2015-04-09 08:41
I cannot reproduce :/ I will do my best to reproduce and fix it but, it would be cool to have the IDBs.

**Comment by joxeankoret** [comment] 2015-04-10 10:05
Should be fixed with 9eb60b7bf95f7a659b8f3d29a83e2d31d6bd2b74

**Closed by joxeankoret** 2015-04-10 10:05 UTC
Labels: bug, question
