### ISSUE TITLE
Hanging during diffing process. 

### ISSUE THREAD

**Issue by Fire30** [joxeankoret/diaphora#150] opened 2019-01-29 03:23 UTC
Hello,

IDA seems to hang during the diffing process and the message that is displayed is:
"[Single Thread] Finding with heuristic 'Same koka hash and contents'" 

It also does not seem to be an infinite loop or anything as my cpu is not being maxed out while it is hanging. I took a quick glance at the code and couldn't really figure out what could be causing it. 

I am on IDA 7.0 on a windows 7 vm if that helps at all. The sqlite databases of the files are also quite large at around ~750MB as well. 

Thanks!

**Comment by Fire30** [comment] 2019-01-29 03:37
![log](https://i.imgur.com/8t9tPvX.png)

Here is a screenshot of the log.

**Comment by Fire30** [comment] 2019-01-29 03:50
I commented out the heuristic in diaphora_heuristics.py, and now it continues a little farther but once again hangs while using 0% of the cpu in the 'same rare constant' heuristic. Not sure what could be causing this.

**Comment by Biswa96** [comment] 2019-01-29 08:48
Exactly same issue in my PC. Windows 10 Pro 64bit + IDA 7 pro + python 2.7.x.

**Comment by joxeankoret** [comment] 2019-01-29 09:46
This is a problem that is happening to many users of IDA versions <= 7.1 with Windows (any version). I'm currently researching why is it happening but the only things I know for sure are the following:

1. Seems not to happen with IDA 7.2.
2. Seems to only happen in Windows.
3. The hang happens when doing some SQL queries involving text search.

**Comment by enovella** [comment] 2019-01-29 11:10
My setup with same/similar bug:
- IDA 7.2
- Vbox Windows 10 

![parallel2](https://user-images.githubusercontent.com/14809754/51904218-049e1600-23b6-11e9-915d-f52d1acf623f.png)

More info at https://twitter.com/enovella_/status/1087549639962722304

**Comment by joxeankoret** [comment] 2019-01-29 11:37
Note to myself: I think it's clear that it involves SQLite + threads. My guess is that by using a new database connection per thread instead of using sqlite3.connect("xxx", check_same_thread=False) should "magically" fix the problem.

Will try to fix it today after work.

**Comment by enovella** [comment] 2019-01-30 00:00
Hey @joxeankoret ,

I couldn't make today but tomorrow I can check this out. Send me whatever you want me to test. Keep up the good job mate!

Agur!

**Comment by joxeankoret** [comment] 2019-01-31 18:24
Bug fixed with 5e60aec88a7af5838491605e46b8c600a96b35d6. If after synchronizing with the repository some of you still reproduce it, please reopen.

**Closed by joxeankoret** 2019-01-31 18:24 UTC

**Comment by silveroxides** [comment] 2023-01-25 18:37
Still an issue and I am using IDA Pro 7.7.
It hangs in intervals, especially at "same name" and "same rare constants".
Diffing already exported 20 to 22 MB aarch64 ELF binaries end up taking on average 6-9 hours.
I know these binaries should not take that long either.
This is the [system](https://pastebin.com/X7uuv6uh) I am running it on and I have encountered this issue every time.

**Comment by joxeankoret** [comment] 2023-01-26 08:23
Hi! IDA 7.7 is too old but, if you can share some binaries, I will take a look to see what happens.

**Comment by silveroxides** [comment] 2023-01-26 12:52
Just these particular binaries would be difficult since they are somewhat confidential and I don't have the clearance to disclose any of these in particular. But I might be able to find something equivalent to run a test on and if you would want any log from diffing i can send both that and the binaries at the same time.

**Comment by joxeankoret** [comment] 2023-01-26 15:31
Binaries would be enough for me to try to reproduce it.

**Comment by silveroxides** [comment] 2023-02-17 09:30
Sorry about the lack of response. I managed to find a method to map out pretty much everything in an ARM database on IDA Pro such as the one made from the binaries I am working with. 
I generate C signature string with wildcard bit mask as well as a matching byte sequence signature for manual searching if needed at 2 or more locations offset from the functions initial address, I then generate at least one C signature and IDA signature for an address referencing the function and choose the best one based on a rating system. 
Signatures generated inside function is preferably based at a series of similar instructions stacked after each other since that generates the most likely unique signature with the least wildcards but the properties for deciding wildcards are balanced enough that most locations work. 
I only need to figure out a method for properly automating the entire process, store it as some form of database and enable basic stuff like names to be imported to another database based on same binary although different version. Funny thing is the Plugin I found for making the patterns were even for IDA 8.1+ but I just back ported it using the IDA SDK without any issues. 
I did find a similar binary if you are still interested in looking at it. I uploaded it to transfer.sh
[libBootloader.so](https://transfer.sh/ELlIQv/libBootloader.so)
