### ISSUE TITLE
File Handle to SQLITE Database not closed

### ISSUE THREAD

**Issue by ionescu007** [joxeankoret/diaphora#5] opened 2015-04-08 16:58 UTC
Hi,

Even after closing the database (IDB), the IDA process still has the handle open to Diaphora's .sqlite database. Even when switching databases, any old exported database remains open. This is probably a missing close() call somewhere in the Python script.

This means, for example, that you cannot re-diff to the same .sqlite file (even after Diaphora asks "do you want to overwrite"?) because Diaphora will already have it open. You need to fully exit IDA and re-open it.

**Comment by joxeankoret** [comment] 2015-04-08 17:09
I think I have a fix for this but I cannot reproduce in Linux. It happens in Windows, right?

**Comment by joxeankoret** [comment] 2015-04-08 18:01
Should be fixed with commit 7a9a6aa6d1fddcd21eef2aac29be318a41c3a81a

**Comment by joxeankoret** [comment] 2015-04-08 18:33
I'm able to reproduce it and the fix doesn't work :/ I will need some time to understand it...

**Comment by joxeankoret** [comment] 2015-04-08 19:10
Bug fixed with e6f4321b7845a6203b4d0891ae9a37c92056e67c

**Comment by joxeankoret** [comment] 2019-01-30 12:17
This issue seems to be the real culprit of this other bug that is turning me crazy: https://github.com/joxeankoret/diaphora/issues/150

**Comment by joxeankoret** [comment] 2019-01-31 18:24
So, is not the real culprit, but both bugs are related. Summary: Attached databases aren't properly detached.

**Comment by joxeankoret** [comment] 2019-02-07 19:35
Should be fixed with a4472f9191ad5b6057bbc5483f1685b3ccf59762

**Closed by joxeankoret** 2019-02-07 19:35 UTC
Labels: bug
