### ISSUE TITLE
Feature Request: Additional heuristic for comparing basic blocks

### ISSUE THREAD

**Issue by moshekaplan** [joxeankoret/diaphora#41] opened 2015-10-21 13:01 UTC
I have two functions that were matched at roughly 75%.

The functions are short and end with an unconditional jump. The only difference between them is the JMP's destination address. But the basic blocks they jump to have the exact same contents and ends with a RET.

Would it be possible to implement a heuristic that considers these two functions to be the same?

Thank you

**Comment by djcatter** [comment] 2015-10-21 18:06
So it is a mater of masking out those JMPs. 

Looking at it further it looks like this is the suspect code:

'''python
          #Original X86 masking code
          decoded_size = idaapi.decode_insn(x)
          if idaapi.cmd.Operands[0].type in [o_mem, o_imm, o_far, o_near, o_displ]:
            decoded_size -= idaapi.cmd.Operands[0].offb
          if idaapi.cmd.Operands[1].type in [o_mem, o_imm, o_far, o_near, o_displ]:
            decoded_size -= idaapi.cmd.Operands[1].offb
          if decoded_size <= 0:
            decoded_size = 1
'''

So the problem is the code is only changing the binary data by a size of 1 and sometimes that address can be in the middle of an operand. So for a quick hack change it too:

'''python
          #Original X86 masking code
          decoded_size = idaapi.decode_insn(x)
          if idaapi.cmd.Operands[0].type in [o_mem, o_imm, o_far, o_near, o_displ]:
            decoded_size = 1
          if idaapi.cmd.Operands[1].type in [o_mem, o_imm, o_far, o_near, o_displ]:
            decoded_size = 1
          if decoded_size <= 0:
            decoded_size = 1
'''

Now additionally you will want to pull down the branch that I had started. The other problem is some of the algorithms look at the assembly patterns in text which also cause problems so I changed the code to remove these addresses.

Derek

**Comment by joxeankoret** [comment] 2015-10-31 11:10
I will take a look to the patch proposed by @djcatter . If it's possible @moshekaplan, could you share IDBs so I can test with your examples?

**Comment by moshekaplan** [comment] 2015-11-01 04:07
Unfortunately, it is not possible to share those IDB's :(

**Comment by joxeankoret** [comment] 2015-11-02 17:58
I will try to do my best to reproduce this behaviour, but without IDB/binaries...

**Comment by joxeankoret** [comment] 2015-11-10 17:11
Unfortunately, I cannot find IDB/Binaries to reproduce this behaviour and changing the decoded_size to just 1 or 0 is overkill, causing too many false positives :(

**Comment by moshekaplan** [comment] 2015-11-10 17:14
I'll try to create binaries with the requisite assembly within the next
week.

Moshe

**Comment by joxeankoret** [comment] 2015-11-10 17:31
Thanks you!

**Comment by joxeankoret** [comment] 2017-12-16 15:44
Closing for now, as I believe the issue was "fixed" with the new heuristics.

**Closed by joxeankoret** 2017-12-16 15:44 UTC
Labels: enhancement
