### ISSUE TITLE
Keep getting crashes in IDA Pro x64 when trying to create an inital database snapshot.

### ISSUE THREAD

**Issue by tekwizz123** [joxeankoret/diaphora#167] opened 2019-07-13 08:05 UTC
Error logs:

Error: 'NoneType' object has no attribute 'commit'
Traceback (most recent call last):
  File "C:/*removed*/Documents/diaphora\diaphora_ida.py", line 2138, in _diff_or_export
  File "C:/*removed*/Documents/diaphora\diaphora_ida.py", line 744, in export
  File "C:/*removed*/Documents/diaphora\diaphora_ida.py", line 669, in do_export
AttributeError: 'NoneType' object has no attribute 'commit'

Trying to do a simple initial database creation for a Windows system file. Running IDA Pro 7.1.180227 if that helps.

**Comment by joxeankoret** [comment] 2019-07-13 12:41
It's very-very odd: it means that no database was opened, thus, the db object was None. Does it happen to you with any binary and all binaries? Does IDA have privileges to create the .sqlite database wherever it tries to create it?

**Comment by tekwizz123** [comment] 2019-07-13 18:49
Hi Joxean,

Yeah this issue appears to be happening for multiple files. I tried running ida64.exe with admin privileges again but no luck. Tried switching over to ida.exe and running that but also had no luck, even when running with administrator privileges. I know the destination directory for the SQL database is in my Documents folder and should be accessible to my current user and the admin user. I also tried with other files such a simple downloaded executable and I am encountering the same error so it doesn't seem to be specific to the fact that I am working with Windows system binaries; the issue also replicates itself even with just a simple installer binary for a simple program.

**Comment by joxeankoret** [comment] 2019-07-15 11:23
It sounds like you have some problem with your IDA+Python installation. Please, try doing the following in the IDA's python prompt:

```
import sqlite3
db = sqlite3.connection("test.db")
print("Db?", db)
```

My suspicion is that it will trigger some sort of error.

**Comment by tekwizz123** [comment] 2019-07-15 14:55
Looks like you might be right, this is my output for the first two commands:

`---------------------------------------------------------------------------------------------
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
Python>import sqlite3
Python>db = sqlite3.connection("test.db")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'connection'`

That being said I did try this and it worked:
`Python>import sqlite3
Python>db = sqlite3.Connection("test.db")
Python>print("Db?", db)
('Db?', <sqlite3.Connection object at 0x0000021912265A28>)`

So perhaps there is a capitalization error? Aka sqlite3.connection vs sqlite3.Connection?

**Comment by joxeankoret** [comment] 2019-07-15 16:00
Sorry, the code I wrote had a typo. I am honestly lost about what can be the problem here. Can you please enumerate all the steps you follow so I can try to reproduce the behaviour?

**Comment by tekwizz123** [comment] 2019-07-15 17:13
Okay so here is what I've done:

1. Uninstalled IDA Pro Version 7.1.180227
2. Uninstalled all versions of Python 2.7. Still have a version of Python 3.7 x64 installed but I doubt this is what is causing the issue, as IDA appeared to be using the Python 2.7 version during testing.
3. Reinstalled IDA Pro Version 7.1.180227 on my Windows 10 machine running Windows Insider Build 18932.
4. Opened up a sample file (in this case an IDB file I took for a win32k.sys file)
5. Tried to run Diaphora. Here is the output:

```
  bytes   pages size description
--------- ----- ---- --------------------------------------------
 17555456  2143 8192 allocating memory for b-tree...
  9306112  1136 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...
-----------------------------------------------------------------
 27123712            total memory allocated

Loading processor module C:\Program Files\IDA 7.1\procs\pc64.dll for metapc...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
Database for file 'win32k.sys' has been loaded.
---------------------------------------------------------------------------------------------
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
Error: 'NoneType' object has no attribute 'commit'
Traceback (most recent call last):
  File "C:/Users/tekwizz123-research/Documents/diaphora\diaphora_ida.py", line 2138, in _diff_or_export
  File "C:/Users/tekwizz123-research/Documents/diaphora\diaphora_ida.py", line 744, in export
  File "C:/Users/tekwizz123-research/Documents/diaphora\diaphora_ida.py", line 669, in do_export
AttributeError: 'NoneType' object has no attribute 'commit'
```

6. Tried to run your command:

```
Python>import sqlite3
Python>db = sqlite3.Connection("test2.db")
Python>print("Db?", db)
('Db?', <sqlite3.Connection object at 0x000001940033AA28>)
```

7. Think about trying a different file and seeing if that works. Load up a small sample rootkit remover installer from MalwareBytes and try running Diaphora again:

```
Possible file format: MS-DOS executable (EXE) (C:\Program Files\IDA 7.1\loaders\dos64.dll)
Possible file format: Portable executable for 80386 (PE) (C:\Program Files\IDA 7.1\loaders\pe64.dll)

  bytes   pages size description
--------- ----- ---- --------------------------------------------
 56713216  6923 8192 allocating memory for b-tree...
 56713216  6923 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...
-----------------------------------------------------------------
113688576            total memory allocated

Loading file 'C:\Users\tekwizz123-research\Downloads\mbar-1.10.3.1001.exe' into database...
Detected file format: Portable executable for 80386 (PE)
Loading processor module C:\Program Files\IDA 7.1\procs\pc64.dll for metapc...OK
Autoanalysis subsystem has been initialized.
  0. Creating a new segment  (0000000000401000-0000000000418000) ... ... OK
  1. Creating a new segment  (0000000000418000-000000000041C000) ... ... OK
  2. Creating a new segment  (000000000041C000-000000000041F000) ... ... OK
Reading imports directory...
  3. Creating a new segment  (0000000000418364-000000000041C000) ... ... OK
Plan  FLIRT signature: Microsoft VisualC 2-14/net runtime
autoload.cfg: vc32rtf.sig autoloads mssdk.til
Assuming __cdecl calling convention by default
Type library 'mssdk' loaded. Applying types...
Types applied to 189 names.
main() function at 406D64, named "_WinMain@16"
Marking typical code sequences...
Flushing buffers, please wait...ok
File 'C:\Users\tekwizz123-research\Downloads\mbar-1.10.3.1001.exe' has been successfully loaded into the database.
IDA is analysing the input file...
You may start to explore the input file right now.
---------------------------------------------------------------------------------------------
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
Type library 'vc6win' loaded. Applying types...
Types applied to 0 names.
Using FLIRT signature: Microsoft VisualC 2-14/net runtime
Propagating type information...
Function argument information has been propagated
The initial autoanalysis has been finished.
Error: 'NoneType' object has no attribute 'commit'
Traceback (most recent call last):
  File "C:/Users/tekwizz123-research/Documents/diaphora\diaphora_ida.py", line 2138, in _diff_or_export
  File "C:/Users/tekwizz123-research/Documents/diaphora\diaphora_ida.py", line 744, in export
  File "C:/Users/tekwizz123-research/Documents/diaphora\diaphora_ida.py", line 669, in do_export
AttributeError: 'NoneType' object has no attribute 'commit'
```

**Comment by joxeankoret** [comment] 2019-07-18 15:09
I'm totally lost with this issue: I cannot reproduce and you're the first and only person that reported this problem. I'm afraid it is specific to your environment.

**Comment by tekwizz123** [comment] 2019-07-18 15:50
Ah well thought that might be the case.. I'll try debug whats up on my side and add some information to this post once I get some more concrete information. Guess the starting point would be to figure out why it doesn't even create the required object in the first place given its trying to use a NoneType object, so I'll probably start there and try work backwards.

Thanks for taking the time for this, and sorry it got you so lost :)

**Comment by joxeankoret** [comment] 2019-07-18 16:08
You're welcome! And feel free to make any question or ask for help to debug your issue.

**Comment by joxeankoret** [comment] 2019-08-06 14:53
Closing for now as I have no new feedback/information. Feel free to re-open if you have any new information regarding this issue.

**Closed by joxeankoret** 2019-08-06 14:53 UTC

**Comment by tekwizz123** [comment] 2019-08-06 15:36
Sorry for the lack of response, been trying to gather some more information about the bug. I added in a few more debug statements into diaphora_ida.py and diaphora.py and got the following output:

`---------------------------------------------------------------------------------------------
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
Opening database!
Opened database successfully!
Error: Self.db is NULL!!!
Error: 'NoneType' object has no attribute 'commit'
Traceback (most recent call last):
  File "C:/Users/tekwizz123/Documents/GitHub/diaphora/diaphora_ida.py", line 2140, in _diff_or_export
  File "C:/Users/tekwizz123/Documents/GitHub/diaphora/diaphora_ida.py", line 746, in export
  File "C:/Users/tekwizz123/Documents/GitHub/diaphora/diaphora_ida.py", line 671, in do_export
AttributeError: 'NoneType' object has no attribute 'commit'`

It appears that for some reason self.db within the function "do_export()" is of type NoneType hence why it is not possible to call its commit() function.

To check this wasn't an error with opening the database I modified the open_db() function in diaphora.py as follows:

`  def open_db(self):
    print("Opening database!")
    db = sqlite3.connect(self.db_name, check_same_thread=True)
    if db is None:
      print("Error opening the database!!!!")
    else:
      print("Opened database successfully!")
    db.text_factory = str
    db.row_factory = sqlite3.Row`

As can be seen in the output above there was no error. I did confirm the _self_ part of _self.db_ is in fact of type CIDABinDiff from the following lines of code in the main() function:

`    bd = CIDABinDiff(file_out)
     ....
    try:
      bd.export()`

CIDABinDiff calls CBinDiff's initializer to set itself up:

`class CIDABinDiff(diaphora.CBinDiff):
  def __init__(self, db_name):
    diaphora.CBinDiff.__init__(self, db_name, chooser=CIDAChooser)`

And if we go to CBinDiff we can see that _self.db_ is initialized by calling open_db(), which is the function that I added additional logging to.

`class CBinDiff:
  def __init__(self, db_name, chooser=CChooser):
    self.names = dict()
    self.primes = primes(2048*2048)
    self.db_name = db_name
    self.dbs_dict = {}
    self.db = None # Used exclusively by the exporter!
    self.open_db()`

So I guess the question that I have would be if it is somehow changing state inbetween the calls, or somehow self is not referring to the right object? I'd also be interested to know if I'm looking at this wrong or making any incorrect assumptions given this is my first time digging into Diaphora's code.

**Comment by joxeankoret** [comment] 2019-08-06 15:50
Really, it makes no sense to me at all how self.db gets set to None or where, honestly.

**Comment by tekwizz123** [comment] 2019-08-06 16:57
Yeah that's fair. I just tested it out on a Windows v1803 VM and confirmed the code is working fine so like you said its probably something locally. I'm going to check and see if perhaps its something to do with Windows versions cause otherwise I'm not really sure what is causing this off the top of my head.

**Comment by tekwizz123** [comment] 2019-08-06 21:37
Okay got this being diffed a bit more between a working installation on a VM and my local install and it appears that the issue seems to partially boil down to the fact that the call is supposively made from the initializer of CIDABinDiff to the initializer of CBinDiff, but despite me placing several print statements within the CBinDiff initializer function, none of them seem to be being executed, but print statements before and after the call to the CBinDiff initializer function are working fine. 

This to me seems to suggest that somehow the CBinDiff intialization function was not being called correctly for whatever reason, hence also why open_db() is called in the working installation on the VM, but not on my local installation. This would also explain why self.db is None, as it is never populated by open_db().

So really the line that isn't executing as expected is this one in diaphora_ida.py:

`diaphora.CBinDiff.__init__(self, db_name, chooser=CIDAChooser)`

No idea why the call isn't working though.

**Comment by joxeankoret** [comment] 2019-08-07 09:26
Maybe there is some old diaphora.py/diaphora_ida.py script laying around somewhere in your Python path?

**Comment by tekwizz123** [comment] 2019-09-02 04:28
Just wanted to say I installed IDA Pro 7.2 as part of some company work and then went back and used IDA 7.1 again with latest Diaphora and it seems to be working again. Don't know what was causing it to fail before...weird.
