### ISSUE TITLE
Error: expected string or Unicode object, NoneType found

### ISSUE THREAD

**Issue by MINIONBOTS** [joxeankoret/diaphora#40] opened 2015-09-15 19:10 UTC
Error: expected string or Unicode object, NoneType found
Traceback (most recent call last):
  File "Z:/Pro/Diaphora/diaphora.py", line 3703, in _diff_or_export
    bd.export()
  File "Z:/Pro/Diaphora/diaphora.py", line 1515, in export
    self.do_export()
  File "Z:/Pro/Diaphora/diaphora.py", line 1509, in do_export
    self.export_structures()
  File "Z:/Pro/Diaphora/diaphora.py", line 1453, in export_structures
    self.add_program_data(type_name, name, definition)
  File "Z:/Pro/Diaphora/diaphora.py", line 1039, in add_program_data
    cur.execute(sql, values)
TypeError: expected string or Unicode object, NoneType found

**Comment by MINIONBOTS** [comment] 2015-09-15 20:14
It was on IDA 6.6., not sure if that matters...

**Comment by joxeankoret** [comment] 2015-09-15 22:31
I cannot support IDA 6.6 and all the others (6.7 and 6.8) because is a nightmare :( I decided to support only 6.7 and 6.8 (the 2 latest versions of IDA) because otherwise I would hate myself.

But if you change this line: https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L1038, with this:

```
values = (str(key), str(type_name), str(value))
```

I think it will work.

**Comment by MINIONBOTS** [comment] 2015-09-16 06:52
Thanks for the quick reply, sadly it didn't change anything :) Time to upgrade IDA I guess :)

**Comment by joxeankoret** [comment] 2015-09-16 07:35
I think so :)

**Comment by MINIONBOTS** [comment] 2015-09-16 07:57
Just Tested it on IDA 6.8, same error ... could it maybe the python version ?

**Comment by joxeankoret** [comment] 2015-09-16 08:08
Uhm... I don't think so. Could you share some IDBs so I can test? You can find my PGP key here http://joxeankoret.com/contact.html

**Comment by MINIONBOTS** [comment] 2015-09-16 09:03
I've sent you an email with a dl-link included.

**Comment by joxeankoret** [comment] 2015-09-16 09:21
I'm exporting, it did not crash so far, but did not finish. I will update this issue when I have more data.

**Comment by MINIONBOTS** [comment] 2015-09-16 09:23
Use the export non-ida functions only option, it should crash in under 1 minute

**Comment by joxeankoret** [comment] 2015-09-16 09:27
Nope: 

```
[Wed Sep 16 11:26:10 2015] Database '/path/to/diaphora/tests/minnions/Gw2.sqlite' removed
[Wed Sep 16 11:26:31 2015] Database exported
```

Which IDA version are you using? Version 6.8.150624 (32-bit)?

**Comment by MINIONBOTS** [comment] 2015-09-16 09:36
This idb was from 6.6 (32 bit), but I also tested the same exe file on 6.8.150413 with the same result.

**Comment by joxeankoret** [comment] 2015-09-16 09:41
My educated guess is that some bug in IDA build 150413 is affecting you. Ask support for the latest version (>150624).

**Comment by MINIONBOTS** [comment] 2015-09-16 09:43
So I take that as "it all worked fine" for you ? In that case, I'll do what you said and also double check my python installation and maybe some other plugin conflicts ...which I doubt, but somewhere the bug must come from :) 
Anyway thank you for your help and I'll reply once more if I found out what caused the issue.

**Comment by joxeankoret** [comment] 2015-09-16 09:45
Yes, it worked for me. I don't think it has anything to do with your Python build or plugins: I really doubt it. With the latest build of IDA, it should work. I will leave the issue open until I have your response.

**Comment by MINIONBOTS** [comment] 2015-09-16 09:45
ok thank you :)

**Comment by xyj1** [comment] 2015-10-07 14:04
Hello, I met the same problem. It is strange that, it can run on the ida6.6 in two days ago, now it suddenly can not work now. Can you help me? Thank you very much!

**Comment by joxeankoret** [comment] 2015-10-07 14:33
With which version did it fail for you?

**Comment by xyj1** [comment] 2015-10-07 14:36
Hello, I've been using the IDA6.6.

**Comment by xyj1** [comment] 2015-10-07 14:39
It can work 2 days before, bur now can not.  is the IDA version of the problem?

**Comment by joxeankoret** [comment] 2015-10-07 14:45
Yes, I'm sure. I do not support 6.6 because I cannot maintain all different versions and sub-versions. You will need to upgrade to the latest version, sorry :( I have no idea why is not working for you in such an old version.

Just in case, did you try this? https://github.com/joxeankoret/diaphora/issues/40#issuecomment-140565429

**Comment by xyj1** [comment] 2015-10-08 00:41
OK, I know. Thank you!

**Comment by joxeankoret** [comment] 2015-12-23 10:57
Sorry, I'm closing it as I cannot reproduce (and 6.6 is not supported).

**Closed by joxeankoret** 2015-12-23 10:57 UTC
