### ISSUE TITLE
Import selected fails (multi selection)

### ISSUE THREAD

**Issue by Harko** [joxeankoret/diaphora#112] opened 2018-02-09 11:32 UTC
How to reproduce:
Tab 'Best matches', sort header 'Name 2', select multiple items and choose command 'Import selected'

   self.bindiff.import_selected(self.items, self.selected_items, cmd_id == self.cmd_import_selected_auto)

self.selected_items and self.items are no longer in the same order when the list gets resorted by clicking on a column header

**Comment by joxeankoret** [comment] 2018-02-13 11:41
It looks like an IDAPython + choosers bug. Let me take a look to it to verify...

**Comment by joxeankoret** [comment] 2018-04-04 11:15
Can you @Harko reproduce it with the latest version?

**Comment by joxeankoret** [comment] 2018-06-17 16:30
Guess we can close it.

**Closed by joxeankoret** 2018-06-17 16:30 UTC
