### ISSUE TITLE
Possible typos and bugs

### ISSUE THREAD

**Issue by Ziv00s3** [joxeankoret/diaphora#212] opened 2021-02-10 13:55 UTC
### Same heuristic? Looks like duplicate
https://github.com/joxeankoret/diaphora/blob/e04ed112e3b76c81812f976e8b6a5649c712e2b9/diaphora_heuristics.py#L650
https://github.com/joxeankoret/diaphora/blob/e04ed112e3b76c81812f976e8b6a5649c712e2b9/diaphora_heuristics.py#L701

### Wrong parentheses?
`{}`->`[]`
https://github.com/joxeankoret/diaphora/blob/e04ed112e3b76c81812f976e8b6a5649c712e2b9/diaphora_heuristics.py#L604

### Numeric constant are checked and added to tuple/dict, but not saved to sqlite

https://github.com/joxeankoret/diaphora/blob/e04ed112e3b76c81812f976e8b6a5649c712e2b9/diaphora.py#L680
https://github.com/joxeankoret/diaphora/blob/e04ed112e3b76c81812f976e8b6a5649c712e2b9/diaphora_ida.py#L1507

### Strings encoding/decoding

UTF-16 strings have wrong representation in sqlite. Like this: "NTFS" -> "NNTTFFSS"

**Comment by joxeankoret** [comment] 2021-02-12 11:23
Thank you very-very-very much for the reports! Most of them are already fixed and I just need to run the tests to verify nothing was broken. The only thing I cannot reproduce is the bug with UTF-16 strings. If you could share any binary where it reproduces, I would be very thankful.

**Comment by joxeankoret** [comment] 2021-03-29 10:31
Closing for now, as I cannot reproduce the UTF-16 strings problem and the other bugs were fixed. Feel free to reopen it.

**Closed by joxeankoret** 2021-03-29 10:31 UTC
