### ISSUE TITLE
diaphora fails to make the diff

### ISSUE THREAD

**Issue by AntonKukoba1** [joxeankoret/diaphora#151] opened 2019-02-03 18:43 UTC
IDA 7.0 export works fine, but when a specify the second sqlite database for the diff, it fails right after exporting:
`[Sun Feb 03 20:38:48 2019] Database exported. Took 42.0569999218 seconds
Error: database diff is already in use
Traceback (most recent call last):
  File "D:/Downloads/diaphora-master\diaphora_ida.py", line 2144, in _diff_or_export
    bd.diff(opts.file_in)
  File "D:/Downloads/diaphora-master\diaphora_ida.py", line 603, in diff
    res = diaphora.CBinDiff.diff(self, db)
  File "D:/Downloads/diaphora-master\diaphora.py", line 2546, in diff
    cur.execute('attach "%s" as diff' % db)
OperationalError: database diff is already in use`
p.s. I did close all IDA instances before running it again to make the diff.

**Comment by joxeankoret** [comment] 2019-02-05 12:21
Did you really close all the IDA instances before doing so? Because it's as if there was still an IDA open from where you did your diff. Can you reproduce it again? Because I cannot reproduce it.

**Comment by kcreyts** [comment] 2019-02-06 07:56
I have the same issue with some arm64 binaries I looked at the other day. Reverting to the commit before multithreading is introduced resolved the issue

**Comment by kcreyts** [comment] 2019-02-06 07:56
Mine was on 7.2

**Comment by kcreyts** [comment] 2019-02-06 09:00
I can reproduce this 100% of the time with only a single instance of IDA open; I reverted to the commit before multithreading was introduced specifically because I couldn't avoid reproducing.

**Comment by joxeankoret** [comment] 2019-02-06 10:13
This is odd. Please tell me the operating system, number of processors, RAM, etc... Also, does it show some error message anywhere? Also, can you run IDA with the environment variables DIAPHORA_PROFILE and DIAPHORA_DEBUG set to 1?

**Comment by joxeankoret** [comment] 2019-02-06 10:16
BTW, if all IDA processes are closed and none is still running in background, there is no way I can think a database would be still locked because there is no process holding any lock.

**Comment by flowswitch** [comment] 2019-02-07 12:01
Same issue, diffing ARM binaries on Win10, quad core, 16Gb RAM

**Comment by joxeankoret** [comment] 2019-02-07 13:16
I can reproduce the bug in Windows. Working on a fix.

**Comment by joxeankoret** [comment] 2019-02-07 19:34
And... the bug should be fixed with a4472f9191ad5b6057bbc5483f1685b3ccf59762

**Closed** 2019-02-07 19:34 UTC
